[server]
headless = true
address = "0.0.0.0"
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
primaryColor = "#00d4ff"
